### ISSUE TITLE
0.16.1 crash when desktop share

### ISSUE THREAD

**Issue by edmundlaugasson** [uTox/uTox#1038]
steps:
Settings
Audio & Video
Video input device -> Desktop
Preview

Then program will close itself.
Using 64-bit Ubuntu Xenial version in Linux Mint 18.2 MATE.

**Comment by termac** [comment]
I got the same problem. 996e2a252042ca20424303e5186f5c98f299d5c2 introduced an unrelated change in the call to  XGetWindowAttributes (see: https://github.com/uTox/uTox/commit/996e2a252042ca20424303e5186f5c98f299d5c2#diff-2875be4a2a3fe6f949de034d334edf39). Reverting that change fixes the video preview for me. (video_win[id] is not the same as *win, because win gets assinged to in the first if statement in the video_frame function)

pull request: #1042

**Comment by robinlinden** [comment]
Fixed in #1042
