### ISSUE TITLE
uTox doesn't build with toxcore-0.2.1

### ISSUE THREAD

**Issue by cwilling** [uTox/uTox#1196]
### Overview

1. uTox version: 0.16.1
2. Operating system: Linux
3. Desktop Environment/Window Manager (Linux/BSD only): xfce

### Issue
With latest c-toxcore (version 0.2.1), uTox build fails at link stage. The reason is that libtoxav & libtoxencryptsave libraries are not included in the link.txt file generated by cmake. I've submitted a PR #1195  which fixes the issue for me. However it is failing the Travis CI testing - I presume because that is still running the previous toxcore 0.1.xxx.

Anyway, until this is resolved we are in the position where latest uTox won't build with latest toxcore.

**Comment by redmanmale** [comment]
It builds just fine (see [Travis; it builds against master branch of toxcore](https://travis-ci.org/uTox/uTox/jobs/356054652#L2285)).

One of the things that brought Toxcore 2.x is release of one single big libtoxcore library instead of separate libtoxcore, libtoxav and libtoxencryptsave like it was before. So there's no need of these in CMakeLists.txt.

Please check your environment, maybe there are some old versions of toxcore installed.
If you still would have problems with building uTox please provide some additional info and we'll figure it out.

**Comment by cwilling** [comment]
OK, I see now. I was using a previous build script for c-toxcore that still used the autotools style build rather than using cmake directly (as the README instructs) which, as you say, builds a single libtoxcore.

Could I suggest the auto tools stuff is removed (or updated)?

**Comment by cwilling** [comment]
Also, will you make a new release soon?

With (now correctly build c-toxcore-0.2.1), released uTox-0.16.1 configuration fails (_TEMP not found), whereas configuration & build works fine in develop branch.

**Comment by redmanmale** [comment]
In both [build instructions](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md) and [build script](https://github.com/uTox/uTox/blob/develop/extra/travis/linux-before.sh#L33) we use cmake for building toxcore.

Yeah, latest release (0.16.1) isn't compatible with Toxcore 0.2.x and I hope there will be a new one soon.
