### ISSUE TITLE
Segv when toggling UDP while in video call

### ISSUE THREAD

**Issue by robinlinden** [uTox/uTox#1198]
Running uTox at commit https://github.com/uTox/uTox/commit/5155b87916cd3d1d45cae5c748ecaea1ec87d652 with Toxcore 0.2.1.

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000052a820 in count_chatlist ()
(gdb) bt
#0  0x000000000052a820 in count_chatlist ()
#1  0x0000000000505670 in tox_conference_get_chatlist_size ()
#2  0x00000000004e5fa4 in utox_audio_thread ()
#3  0x00007ff8e39db0a2 in msvcrt!_beginthread () from /cygdrive/c/WINDOWS/System
32/msvcrt.dll
```

**Comment by GrayHatter** [comment]
... this isn't a uTox issue ...

**Comment by GrayHatter** [comment]
I take that back, this could be a race issue, if it happens again with debugging symbols, get the line number. in toxcore

Otherwise, if someone feels the need to fix it before that, then you can pause the av threads while toxcore is restarting.

If it's consistently reproducible  it's a toxcore issue, it should be validating the tox object.

**Comment by robinlinden** [comment]
Yeah, what I figured was that we kill Toxcore and after doing that, we call some function in our audio thread, passing that function our now dead Toxcore instance.
