### ISSUE TITLE
Implement all required points in the Tox Client Standard

### ISSUE THREAD

**Issue by endoffile78** [uTox/uTox#1274]
https://hcoop.net/~docelic/tcs_full.html

**Comment by GrayHatter** [comment]
No, a lot of the points in the TCS that we ignore is because they're stupid points, or not uTox's job

**Comment by frink** [comment]
Which points are stupid?

**Comment by GrayHatter** [comment]
The one's we haven't implemented :D

**Comment by frink** [comment]
_Here is what is marked as **NO** at the [URL above...](https://hcoop.net/~docelic/tcs_full.html)_

**Avoiding False Security:**
1.0.2 - Warning user IP may be exposed when proxy is set
1.0.3 - Enforcing proxy when force proxy is set

**Standardizing Avatar Usage:**
2.2.6 - Standardizing expectation of square avatars
2.2.10 - Broadcast avatar removal to honor user intent
2.2.11 - Conforming to expected use of avatars

**Avoiding Group Spam:**
3.2.1 - Explicit acceptance of group chat inclusion
3.2.2 - Defaulting auto-accept of group inclusion to false

**Avoiding Data Loss:**
3.2.3 - Warning user of data loss before leaving a group

**Ensuring Honoring Privacy:**
3.3.3 - Defaulting auto-answering calls to false

**Avoiding Shared System Privacy Breach:**
4.0.2 - Defaulting to message persistence to false
5.0.1 - Exposing the option to encrypt .tox data file

**Providing Easy Data Access:**
5.0.2 - Exposing the option to decrypt encrypted profile data
5.0.3 - Storing profile data in standard locations

_I don't understand how these are against the goals for uTox. - What am I missing?_

**Comment by GrayHatter** [comment]
An IP isn't protected information. And if you have a threat model where it is, you need to be tunneling everything through an onion router.

Avatars shouldn't be standardized, clients should make a best effort, to display whatever it gets.

IIRC, that was fixed

That's a problem that needs to be fixed with toxcore, not uTox

uTox dosen't auto answer calls -_-

No, message persistence is a feature, not a bug

That is an option

already done.

The info from  is BADLY out dated, and in some places simply wrong.

The goals for uTox are to be usable for sane humans... Paranoid/security nerds need not apply, and shouldn't be the ones writing standards. That being my original issue with TCS.

**Comment by frink** [comment]
_Not sure what some of your statements where addressing since they lack any references._

Here's my best guess at matching your replies...

**Avoiding False Security:**
> An IP isn't protected information. And if you have a threat model where it is, you need to be tunneling everything through an onion router.

But proxying is another means to obscure an IP and should warn the user if it the data is not going through the proxy as expected. Shouldn't we imply proxy services be desired if a proxy was entered? Based on that implication, isn't it fair to notify that the proxy is not being forced? _(granted, 1.0.2 is worded a little strange)_

_1.0.3 does not seem to be addressed..._

**Standardizing Avatar Usage:**
> Avatars shouldn't be standardized, clients should make a best effort, to display whatever it gets.

Avatars may not be standard and the app SHOULD show what it gets. But most apps do EXPECT a 1:1 ratio for avatars. Is it really unreasonable to warn the user that their new avatar is not a standard size?

_2.2.10 and 2.2.11 do not seem to be addressed..._

**Avoiding Group Spam:**
> IIRC, that was fixed

So [the page](https://hcoop.net/~docelic/tcs_full.html) has it wrong on 3.2.1 and 3.2.2?

**Avoiding Data Loss:**
> That's a problem that needs to be fixed with toxcore, not uTox

So ToxCore needs to show the client an alert before leaving a group?
That doesn't seem like the job of ToxCore to do anything related to the user interface...

**Ensuring Honoring Privacy:**
> uTox dosen't auto answer calls -_-

So 3.3.3 is also erroneously reported?

**Avoiding Shared System Privacy Breach:**
> No, message persistence is a feature, not a bug

So defaulting to message persistence to off **is not an option** because you want them to persist?

> That is an option

So 5.0.1 are erroneously reported?

**Providing Easy Data Access:**
> already done.

So 5.0.2 and 5.0.3 are erroneously reported too?

- - - -
**Conclusion:**
> The info from is BADLY out dated, and in some places simply wrong.

So the **items marked wrong** are:

- 3.2.1 - Explicit acceptance of group chat inclusion
- 3.2.2 - Defaulting auto-accept of group inclusion to false
- 3.3.3 - Defaulting auto-answering calls to false
- 5.0.1 - Exposing the option to encrypt .tox data file
- 5.0.2 - Exposing the option to decrypt encrypted profile data
- 5.0.3 - Storing profile data in standard locations

And the  **items considers stupid** are:

- 1.0.2 - Warning user IP may be exposed when proxy is set but not forced
- 1.0.3 - Enforcing ONLY proxy use when force proxy is set
- 2.2.6 - Standardizing expectation of square avatars
- 2.2.10 - Broadcast avatar removal to honor user intent
- 2.2.11 - Conforming to expected use of avatars
- 3.2.3 - Warning user of data loss before leaving a group
- 4.0.2 - Defaulting to message persistence to false

_Did I parse your message correctly?_ :-D

- - - -

**Commentary:**
> The goals for uTox are to be usable for sane humans... Paranoid/security nerds need not apply, and shouldn't be the ones writing standards. That being my original issue with TCS.

_I'm confused by this because it seemed that Tox was created precisely for paranoid security nerds..._

> From **[About Tox](https://tox.chat/about.html):** 
> Tox began a few years ago, in the wake of Edward Snowden's leaks regarding NSA spying activity. The idea was to create an instant messaging application that ran without requiring the use of central servers. The system would be distributed, peer-to-peer, and end-to-end encrypted, with no way to disable any of the encryption features; at the same time, the application would be easily usable by the layperson with no practical knowledge of cryptography or distributed systems. 

- Based on the above description it seems that forcing proxy use (when set by user) and avoiding unencrypted persistent messages (by default) and broadcasting the unset of user's avatars - _the are really expected features of Tox clients..._

- As for the non-security nerd stuff, warning user of unintentional consequences (on leaving groups or when not using a set proxy) and responding to avatar changes in a normal way - _these seem fair and reasonable to me..._

- It seems unfair to dismiss sane defaults for a security-focused instant messenger or to dismiss layperson's expectations of usage as unreasonable. But I guess this is all a matter of perspective...

- I'm also surprised to learn that a Tox client hates security nerds. I guess that's allowed. Just unexpected...

_Thanks for the in-depth response! Cheers!_
