### ISSUE TITLE
utox.io dead? update binaries.

### ISSUE THREAD

**Issue by fcore117** [uTox/uTox#1289]
Please update utox.io with some releases or at least make daily builder working so newcomers can test fresh uTox without looking old version.

**Comment by GrayHatter** [comment]
uTox.io is capable of running scripts, if anyone wants to write an auto build system. I'm happy to review and install in so the server can generate it's own nightlies.

**Comment by redmanmale** [comment]
We already have several build systems (build.tox.chat, travis, appveyor) and writing yet another one doesn't look like a good idea to me.

I understand your security concerns about shipping third-party build binaries though.

So if we cannot automate build process (more or less effortlessly) how about build release binaries by hand? We have a new release couple times in a year. It's not very frequently to be painful.
With the source release we will also build new bins, upload them to the uTox.io and the Github release.

@robinlinden @endoffile78 Thoughts?

**Comment by envsh** [comment]
Any new release tag? https://github.com/uTox/uTox/releases

**Comment by Tcll** [comment]
no linux appimages??

**Comment by GrayHatter** [comment]
Sorry, had to delete your link, I don't allow 3rd parties to distribute binaries on any of my projects...

As far as building from source; I think that's a perfectly reasonable expectation from alpha stage software... But even if it wasn't toxcore, and by extention uTox have mostly stalled in development. We just had a conversation about this on IRC, and the conclusion was that no one felt like uTox was deserving of a new release. (Nor did anyone have the time/energy to pull together everything needed to make one.)

**Comment by Tcll** [comment]
I find my links pretty credible (you could MD5 or so compare the download and find no differences), but I understand. ;)

and that's a shame, we can't exactly rely on distros to do their part
I still have Xubuntu 16.04 installed on 1 machine, and the latest utox version I can get there is 0.16.1
and Void Linux provides an outdated 0.17.0 build (check my issue where it deleted my profile)

to add though, appimages are better than distro-installs anyways due to their portability
if something happens to my OS, I have my programs on a separate drive
with a distro install, I'd lose utox, where I wouldn't with an appimage.

what's holding back utox from being released (aside from laziness)??
the void linux release (while I had that minor hiccup) is FAR better than the 0.16.1 appimage
despite it's random crashes and call drop issues the only thing it has worse from 0.16.1 is group chat support now almost always crashes the client (there was 1 case it worked until my friend froze me from mass file transfers)

I assume quite a bit of that has been fixed though since my version is outdated

**Comment by fcore117** [comment]
Seems that only thing that could push Tox/uTox to development again is some sort of Snowden like scandal that rattles world. Currently everyone are in comfy zone with their favorite IM app that just works™. Worst is that 95% of IM apps are heavy bloatware built upon Electron/Node.js and uses central servers that ddos takes easily down(Telegram got ddos-ed in China some weeks ago)

Now at least there is Tox like it is now thanks to all current and past developers.

**Comment by avoidr** [comment]
>Seems that only thing that could push Tox/uTox to development again is some sort of Snowden like scandal that rattles world. Currently everyone are in comfy zone with their favorite IM app that just works™.

Nah. You already said it; People only care that it *just works™*. Not some silly esoteric human rights.

**Comment by Tcll** [comment]
well I mean...
after being attacked on Discord and putting up with the joke of a staff team there (their "security" is a lie)
I got tired of my profile being hacked (never gave away my token), my PC being ratted (thanks to electron), and have no trust in anything that's not P2P
I don't use qtox because it looks like a RAT over the network (UDP traffic galore, even when disabled)
and just prefer utox in general due to the low resource usage I need.

I WOULD work on utox myself, but I've got my own hunk of a huge project to manage, and am already working on my own chat plugin for that to replace literally everything under my own secure (intrusion preventing, encrypted, anonymous (not even friends can know your IP)) P2P network protocol.

though of course, the issue with that is it won't be functional for a few years, which is why I still need utox while I work on it.

everything else sucks, nobody knows the meaning of "security", and everyone big uses bias against their users, nothing else is trustworthy, not even Matrix.

I can't recommend RetroShare as a replacement due to it's broken DHT over IPv4 when ISPs use IPv6
Jami is only in Alpha stage and kills my machine
and of course other tox clients aren't even worth the effort

sometimes I feel like the only one actually doing any sort of work to improve the internet u.u
