### ISSUE TITLE
Add a warning in XP builds that uTox is best effort, and shouldn't be considered secure.

### ISSUE THREAD

**Issue by GrayHatter** [uTox/uTox#1341]

**Comment by victordesfe** [comment]
wait, what?

**Comment by GrayHatter** [comment]
The warning should state that uTox while itself intends to be secure... Users shouldn't expect it to protect them while running on Windows XP...

I don't want people thinking that uTox can make using an insecure system secure.

**Comment by victordesfe** [comment]
If you want to show a warning message, it must also be added to people using utox in old versions of Mac OS X and linux users in an older kernel version. Impying Windows XP is the less safe is subjective since there are also known vulnerabilities on old macos and old linux kernel versions, and you don't know which vulnerabilities affects most utox privacy & security.

Even with new operating systems, security can be compromised critically ([a recent example](https://www.bleepingcomputer.com/news/security/patched-windows-zero-day-provided-full-control-over-vulnerable-systems/)), so in that hypotetical case you should also warn Windows Vista, 7 and 8 users who doesn't enable updates.

I think the best thing to do is to add a warning in the website before downloading, it would be enough. The warning will only show if you are browsing from an outdated OS (via user agent detection). Adding an in-app warning would be a bad move IMO since it'll be annoying.

**Comment by GrayHatter** [comment]
No, as there's **no way** for a normal user to upgrade to fix XP security defects... The same is NOT true of other operating systems.

**Comment by ihatewin10** [comment]
if you want a example of security defects you have windows 10. It is updated only although you say cancel....

**Comment by victordesfe** [comment]
fix mac os x 10.6 security flaws? it was abandoned even before windows xp (2013), and it is as closed as windows in terms of kernel and source. Even windows xp have been receiving updates through Windows Embedded POSReady 2009 (it has been reciving security updates since last month), and i'm neither including community made service packs and fixes...

IDK what are you smoking, it seems you only want to piss off windows xp users by the fact that they are using that system, to be honest. Wanting to add the message only and exclusively for windows xp would be of a total jerk person (if you'll forgive this expression). Even windows vista has been without updates for a complete year, and windows 7 is going in 2020.

**Comment by ihatewin10** [comment]
also when it left windows 10, to the month they classified to windows XP of unsafe.....Just because it is old some people say that windows XP is bad.....Come on is all a lie. Windows XP is safe it hurts to who it hurts

**Comment by GrayHatter** [comment]
Woah, what did I step in here?!

No, I'm not going to change my mind on this. I'm not willing to put time into trying to support an OS that I know is insecure, getting more insecure. Claiming that other operating systems aren't secure isn't going to change XP.

All of that said, I'm not doing anything to deliberately end uTox working on XP. Anyone is free to continue compiling uTox on XP. The warning is to make it clear to anyone who's life/safety would depend on the security of Tox, that something is wrong.

@ihatewin10 windows 10 is unrelated to this conversation, and forced updates while I agree with you can be problematic. Is NOT a discussion for this thread. Please don't try to bring your irrational dislike for Win10 into unrelated topics.

**Comment by Tcll** [comment]
I hope you don't mind a little friendly interjection :)
I think those who continue to use WinXP either know it's insecure and refuse to update, are too incompetent to understand how to really use a computer, or for businesses, just don't have the forethought enough to put money towards buying new systems.

That aside though, as someone who used to hack his own XP to do more with it,
I want to say that yes it's perfectly possible to patch certain exploits.
XP may be insecure with exploits that'll never be patched (arguable), but that doesn't automatically make 10 more secure than XP just because it's newer, when it clearly has far more backdoors.
Microsoft is a company that fixes security holes by renaming files (which common sense says doesn't fix anything)

I no longer use Windows, but I want someone to prove to me that Win10 is more secure than WinXP64
cause as far as I know, ever since Microsoft built Aero, their OSs have gotten less and less secure with every release.
heck, you can hack Win7 with JavaScript, even after deleting internet explorer from the HDD using another machine.

anyways, I'm not here to change your mind about utox (as long as it's a notification displayed on your profile page or something and not an annoying popup)
I actually highly respect those who continue to support XP ;)
but I just want to offer my 2 cents from a hacker perspective of things :)

**Comment by GrayHatter** [comment]
@Tcll your perspective is helpful, and welcome.

**Comment by FrostKnight** [comment]
> I hope you don't mind a little friendly interjection :)
> I think those who continue to use WinXP either know it's insecure and refuse to update, are too incompetent to understand how to really use a computer, or for businesses, just don't have the forethought enough to put money towards buying new systems.
> 
> That aside though, as someone who used to hack his own XP to do more with it,
> I want to say that yes it's perfectly possible to patch certain exploits.
> XP may be insecure with exploits that'll never be patched (arguable), but that doesn't automatically make 10 more secure than XP just because it's newer, when it clearly has far more backdoors.
> Microsoft is a company that fixes security holes by renaming files (which common sense says doesn't fix anything)
> 
> I no longer use Windows, but I want someone to prove to me that Win10 is more secure than WinXP64
> cause as far as I know, ever since Microsoft built Aero, their OSs have gotten less and less secure with every release.
> heck, you can hack Win7 with JavaScript, even after deleting internet explorer from the HDD using another machine.
> 
> anyways, I'm not here to change your mind about utox (as long as it's a notification displayed on your profile page or something and not an annoying popup)
> I actually highly respect those who continue to support XP ;)
> but I just want to offer my 2 cents from a hacker perspective of things :)

To be honest, this is why I have ditched *ALL* windows operating systems in favor good ol, linux. :)

Your response was brilliant. :) 

I was none to pleased with the way this argument went when I saw it, but you showed me once again that some people are smart. 👍 Thank you.

One thing though, you forgot to mention windows 10 can remotely disable your hardware if they disagree with your usage of it, whether legal or illegal. Whether it is hardware, or software that it is running.  

Anywho if GrayHatter sees this post, let him know, I agree with points from both of you.

Windows xp is crap, but then so is windows 10.

**Comment by Tcll** [comment]
Being brought back to this
Honestly, I think a non-intrusive security warning put into the windows build as a whole would be much more viable to get users to look into more secure options, if I haven't changed your mind :)
tbh, I kinda like the idea **"Warning: you're using Windows, don't expect security"** (not like that of course) X3

But I want to add, I'm not sure how safe Linux is either, since Microsoft has been a platinum member for more than a few years, and Canonical (Ubuntu) can be expected to become a partner within a few years.
(**that's not final**, they could change directions, it just doesn't seem likely since they're blinded by money)

The more of this I see, the more I see Microsoft assuming full control over Linux to do the same trash to it they did to Win10, controlling users, collecting data, lying about security, and so on.

The only REAL options I see for a secure OS is either Arch-based Linux distros (without systemd) or FreeBSD.
(there's probably more I'm not aware of)
But, sadly, none of these are even viable enough to recommend to your average noob (Manjaro *maaaaaybe*, but still needs *some* hand-holding)

> I was none to pleased with the way this argument went when I saw it, but you showed me once again that some people are smart. +1 Thank you.

I try to be as informed as I can be, which isn't exactly easy when you try to focus on more topics than average...
But yeah, definitely felt I needed to clarify a bunch of stuff here.
You can't really know too much about security unless you delve into the black-hatter side of things to know how they affect you.
That and constantly re-questioning just how secure things are vs how they claim to be (eg the suicidal platform Discord)
I should probably note I'm also involved with Comodo security solutions, so I have some references for extra knowledge as well :)
And finally, if that ain't enough, I'm also working on a few of my own projects aiming to be secure (including my own metal-level automated (not AI) network protocol, since nothing can be trusted) ;)

You won't find anything of mine here though, I pulled all my projects when GitHub partnered with Microsoft.

Anyways, all of that is just to prove my word isn't really nothing ;)
but I'm afraid I can't really provide references like I want to.

**Comment by FrostKnight** [comment]
Right on, systemd is a pile of crap. xD and yeah, Ubuntu isn't my style either, in my opinion arch based distros aren't the best either, but I use an arch based distro, the difference? it uses openrc by default and has a focus on stability, security, privacy and being 100% libre.
Hyperbola.info
I do have a ubuntu derivative on one laptop, but I really, hope to change that in the future...
This one is called Trisquel.  Sadly that has systemd too.  But yeah, I like the fact that you understand the menace of systemd(on't.)
Ultimately though, I think linux will try to resist giving into microsoft's corruption.  Microsoft may cause some damage but I am hopeful, that most of it will fail.

**Comment by avoidr** [comment]
Windows XP support has been removed in #1407 and a note about it has been added to last release's (`v0.17.2`) release notes.
