### ISSUE TITLE
Windows XP support.

### ISSUE THREAD

**Issue by username1565** [uTox/uTox#1454]
### Overview

1. uTox version: All
2. Operating system: Windows XP
3. Desktop Environment/Window Manager (Linux/BSD only): XP

### Issue

Why the supporting of Windows XP is discontinued?
uTox.exe v0.17.2 was been sucessfully compiled for Windows XP!
See this issue: https://github.com/username1565/uTox_winXP/issues/4 and relevant of this.
Maybe this info can help you to fix something.

**Comment by Barracuda72** [comment]
https://github.com/uTox/uTox/issues/1333#issuecomment-468785564

But you probably have seen this already as you replied there.

Mainstream support for XP ended 11 years ago.
All kinds of official support - 6 years ago.
Even hacky updates from POS versions were discontinued last year.

XP is long dead. Stop necromancy and let it RIP. If you don't like Windows 10, move to Linux - it's much better and secure alternative.

**Comment by username1565** [comment]
@Barracuda72, my Windows XP SP3 working from 2002 year without any updates, and I don't want to change my Operation System, because Edward Snowden was talking about total surveillance, in 2013 year.

**Comment by Barracuda72** [comment]
@username1565

> Windows XP SP3 working from 2002 year without any updates

Are you sure? SP3 came out only in 2008.

> This means hardware and software backdoors.

And why you are assuming that there's no backdoors in XP? I'm absolutely sure there's a couple, if not dozens. Things got even worse with XP going EOL. Now it's just an old, rusty piece of proprietary code not only with backdoors, but also with vulnerabilities that'll never be fixed. And it's also are not supported anymore by major toolchains, that meaning each month there will be less and less software developers targeting it.

If you are that afraid of backdoors - even more reasons to go free software. It can't guarantee a total absence of them, but at least it provides a chance someone noticing and fixing them.

To be clear: being security concerned and at the same time use very old and unsupported closed-source system just doesn't make any sense to me.

**Comment by username1565** [comment]
![2aca726bdbae8c5c83f71cc372d5a9a8_os_share_0310](https://user-images.githubusercontent.com/39200328/82349728-25530a80-9a03-11ea-9c5f-0f003e10538f.jpg)

**Comment by Barracuda72** [comment]
@username1565 

That chart is from 2010; it's ten year old. More relevant data can be found here:
https://www.w3schools.com/browsers/browsers_os.asp
(Yep, I know, that's counting only tech-savvy users and web-developers, but still.)

There should be the clear barrier for backward-compatibility. Beyond that it'll become more of a burden than a good thing. Well, turns out current barrier is Win7. That's still more than 10 years old EOL system, BTW.

Nobody consciously _makes_ code incompatible with XP; they just stop testing it on that system and don't apply fixes and workarounds. You could keep you own fork for this, merging all the new stuff from upstream.

**Comment by username1565** [comment]
@barracuda72, ok.
I already made [this my fork](https://github.com/username1565/uTox_winXP),
but I'm not developing this.
Just if program woking on Windows, this must to be runned for all versions of windows.

**Comment by endoffile78** [comment]
@username1565 Linux is free and open source software and does not have any backdoors built in to it, there is no way to know for sure that Windows does or does not have backdoors in it. If you are worried about newer versions of Windows having backdoors in it then switch to Linux, it will always be supported since grayhatter, avoidr and I use Linux full time and robinlinden uses it partially at least if not full time. There's a higher chance of a backdoor being in Windows XP than there is ever being a backdoor in the Linux kernel.
