### ISSUE TITLE
Align chat text the modern way

### ISSUE THREAD

**Issue by eandmsz** [uTox/uTox#1459]
New Feature Request:

### Align chat text the modern way:
  Your text: **Align Right**
  Contact's text (all contacts in group chat): **Align Left**
  System messages like new day, or call duration, missed calls, etc: **Align Middle**

### Reasoning:
1. Separating the chat to two sides gives much better readability of a conversation.
2. Separating the chat also gives the ability to put delivery notification for each message below the sent messages.
3. Bubbles separate text from background which looks nice and functional as well since it's easier to find a specific text in the history (because you know the size of bubble you are looking for). However the bubbles take a bit more space than just a single line of text, therefore the chat will be less compact, but it will be cleaner and more readable.

See the screenshots below to see how it's done in WhatsApp, Viber, Skype.

### Pre-Analysis:
- WhatsApp only indicates the contact's name in the header which is not very good as you can easily lose track who you are talking to.
- Viber puts the contact's avatar before the text, which is a great idea to make the chat more user friendly.
- Skype puts both the avatar before the text and the name above the text together with the timestamp, which is probably the best way as it suits group chats as well.

They all use a nice way to indicate the message delivery:
- Sending/Pending (one gray tick)
- Delivered (two gray ticks)
- Read/Displayed (two blue ticks)
Skype only shows the read indicator by putting the contact's mini avatar below your messages, which is a great idea for group chats, however they can do this because they generate a custom avatar for all users based on their initials when there is no avatar image uploaded.

uTox doesn't support Read/Displayed status, and it's probably good this way as it somewhat intrudes on your privacy, and it would be a lot of extra work to implement anyway.

### Suggested implementation:
1. Given the GUI framework uTox uses it might be too hard to properly implement bubbles (with nice rounded corners, etc) and would probably require to change the skins as well, so this is a strech goal.

2. Timestamps and Contact name in chat window should have the same font size, which is smaller than regular chat text.

3. Contact's name should be on top of their new messages, aligned left, while timestamp should be under the message, aligned right.

4. Contact's avatar should be in front of their new messages aligned left (see mockup).

5. We should not show our own name since our text is always on the right side.

6. Multi-line text should be wrapped at somewhere between 50% and 75% of the chat window width. This probably needs some extra work since right now the window itself which wraps the text.

7. Sending/Pending text status to be shown as it is right now, simply with a different text color (COLOR_MSG_USER_PEND)

8. Delivered status changes the text color (to COLOR_MSG_USER) as it is right now. As an extra delivery indicator, we should put the contact names's first letter under your text surrounded by a little circle with bg color: COLOR_BKGRND_ALT and with the same font color as what the contact text has (would be very useful in group chats).

9. The contact's typing notifications doesn't need to change anything.

### Screenshots:
WhatsApp
![whatsApp](https://user-images.githubusercontent.com/34283919/81054649-76bdae80-8ec7-11ea-8cf8-d0129467e17c.JPG)
Skype:
![skype](https://user-images.githubusercontent.com/34283919/81054652-77564500-8ec7-11ea-8e8a-3445dece4a28.JPG)
Viber:
![viber](https://user-images.githubusercontent.com/34283919/81054653-77564500-8ec7-11ea-876a-1d170b10a32f.JPG)

**Comment by eandmsz** [comment]
Here is how uTox looks right now:
![uTox_orig](https://user-images.githubusercontent.com/34283919/81062721-c8ba0080-8ed6-11ea-8042-d938c63c787b.png)

And here is a mockup on how it would look with the new alignment (without bubbles):
![uTox_mockup2](https://user-images.githubusercontent.com/34283919/81062756-d66f8600-8ed6-11ea-9ed4-176fd759aafc.png)

**Comment by avoidr** [comment]
Thank you for your elaborate description of your issues, they're all great!

However, I don't think this would be a good UI.

This right and left bubble UI is acceptable for narrow screens, like phone screens, because the distance between them is not too big. But as soon as you have a wide screen — which desktop/laptop monitors nowadays are — it starts to become tedious to jump with the eyes left and right. I don't find that comfortable at all. Even just your screenshots, which seem to have been taken on a tablet, the distance is already miles apart. Even the mockup, it's the default uTox window size, and it's much distance. And the problem only gets worse when you consider tiling window managers, which are quite popular among Linux users — if uTox is the only window on the screen, it takes up all the screen; with the bubble UI, messages are at both edges of the screen. With the current UI, messages are always exactly one line height apart, constant.

If you find the distance between messages makes it hard to distinguish what message is whose, perhaps what you really want is a different theme that makes it clearer. I find the dark theme accomplishes this perfectly, it has good contrast between messages while still being readable against the background. If you don't find the themes readable enough, you can create your own.
(I agree that the default theme makes it hard to look at (not even talking about distinguishing messages), but that's the fundamental problem of putting white background on computer screens. It works for print, not for computer screens.)

The bubble UI bloats up the view vertically. That's acceptable on a vertical screen, but on a wide screen, vertical space is more valuable, and horizontal space is in abundance and unused. So that UI would "free up" (not at all) horizontal space, while bloating up vertically. The better thing to do would be making use of all that unused horizontal space.

>Bubbles separate text from background which looks nice and functional as well since it's easier to find a specific text in the history (because you know the size of bubble you are looking for). 

The right solution is to add a search feature which is easily and efficiently accessible. You're really searching for known text, after all, not bubbles. uTox should have this feature in the future.

**Comment by eandmsz** [comment]
Thank you for your comments. I agree with all of them.
I have made the screenshots on a Windows machine, but they were indeed not fullscreen, because as you said: this side-by-side alignment is not really suitable for wide screens.
All these messengers try to minimize the impact of this by artifically increasing the margins on the left and right of the chat space, but is a really clunky way of solving this problem and actually wastes a ton of horizontal screenspace.

I'm actually making some nice new themes, because I'm not satisfied with the looks of uTox right now. You can expect a pull request for those in the coming weeks.

We can close this issue.

**Comment by avoidr** [comment]
Awesome, thank you!
