### ISSUE TITLE
Crash on open proxy

### ISSUE THREAD

**Issue by dbyoung720** [uTox/uTox#1495]
### Overview

1. uTox version: 0.17.2
2. Operating system: WIN10X64

### Issue

Write your issue here.

**Comment by avoidr** [comment]
Please generally try to describe more what you do to make it crash.

I believe it was already fixed in this commit: 92102bf65c80121cde73f3c192c3315cf3e4cfba
It fixes the crash when you change network settings. Is this the problem that you're having?

There will be a new uTox release this weekend, so this will be fixed.
Thank you.

**Comment by avoidr** [comment]
This is probably already fixed.
