### ISSUE TITLE
uTox the best

### ISSUE THREAD

**Issue by SonOfSnowden** [uTox/uTox#1528]
Hello dear, please tell me why uTox uses UDP data transfer protocol? it is not secure, TCP is much more secure. Is it possible to completely disable UDP protocol in uTox for security reasons?

Best regards, Snowden's extramarital son

**Comment by eandmsz** [comment]
Security and encryption is done in the higher layers. TCP and UDP are just transport protocols and they have nothing to do with security.
TCP is used for reliable packet transfer (with lots of handshaking and retransmission if a packet was lost somewhere), but it can introduce latency, while UDP is just a simple "send and forget" method, which is the fastest and lowest latency way of sending packets. If a UDP packet has been lost somewhere we don't send it again, but it doesn't matter because for real time applications  (like audio/video calls) the data is time sensitive, so you either receive it in time or it's too late to receive it anyway.

You can read more here: [https://www.howtogeek.com/190014/htg-explains-what-is-the-difference-between-tcp-and-udp/](https://www.howtogeek.com/190014/htg-explains-what-is-the-difference-between-tcp-and-udp/)

**Comment by avoidr** [comment]
Really good, @eandmsz, thank you!

Also, @SonOfSnowden, uTox allows you to disable UDP in the settings, in the "Advanced" tab. It also allows you to set a SOCKS5 proxy, which will also forward UDP packets, if that is what you want.

Thanks.

**Comment by GrayHatter** [comment]
@eandmsz excellent description, thanks mate!
