### ISSUE TITLE
antox vs utox message does not come!

### ISSUE THREAD

**Issue by gekon02** [uTox/uTox#1539]
### Overview

1. uTox version: 0.18.1
2. Operating system: windows 10
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

Write your issue here.
The friend will send me a message from my mobile (Antox) when I'm not online. The message does not do it after switching on the Utox!
Please repair: From Antox sends a friend message when I'm offline. When you turn on the Utox, the message does not come!

**Comment by eandmsz** [comment]
Tox works in a peer2peer basis, which means there is no server that stores messages while you are offline. You can only send messages when both parties are online.

If the sending client detects that the message was not delivered then of course it could resend it when the other side becomes available again, but this is up to Antox to implement and I'm not sure if it's possible at all.
I think the receiver side in the Tox protocol does not necessary need to send a delivery notification to the sender, and if this is the case then it's not possible to implement resending a message in a reliable way.

**Comment by robinlinden** [comment]
@eandmsz is correct about that resending messages and keeping track of which messages are delivered has to be done on the sending client. It is very possible to do, and I think all major clients implement it. Not sure about Antox specifically as it's been unmaintained for a few years now, but in [aTox](https://github.com/evilcorpltd/aTox) it's done here:

https://github.com/evilcorpltd/aTox/blob/57e5419c0402ea3179af4a10b20324dd73405cbc/atox/src/main/kotlin/tox/EventListenerCallbacks.kt#L82-L98

**Comment by zoff99** [comment]
@eandmsz please do not use Antox anymore, it has not had meaningful updates since 2017

for an Android client with full features use:
https://f-droid.org/en/packages/com.zoffcc.applications.trifa/

**Comment by GrayHatter** [comment]
Just to be clear... @eandmsz I would *never* user trifa. It's a buggy hot mess with numerous issues, many of them I'd consider critical security, privacy, or data protection issues. The only client on android I would recommend is aTox. TRIFA is a broken, insecure example of what **never** to do. Everyone should avoid it completely!

@zoff99 you know I don't like your client and have tried to talk to you many time about how broken it is, and how it's a dangerous thing to play with other peoples safety/privacy. So that you would try to promote your IED on one of my repos is shocking. Don't inflict the suffering that is trifa others, especially not on my repos. If you try to promote your broken stuff again before you fix your security issues, **and** stop destroying/deleting user data; I'll just ban you from the repo. Please don't make me do that.

@gekon02 I'm pretty sure the issue is what @eandmsz and @robinlinden  described. Both people need to be online. If that's not the problem, please feel free to open a new issue.
