### ISSUE TITLE
Version 0.4.2 broke Group Call

### ISSUE THREAD

**Issue by Serg86** [uTox/uTox#34]
With version 0.3.2 group chats worked, even cross-client with qTox. In version 0.4.2, you can chat via text, but voice chat can't be started. The symbol stays greyed out. qTox is also not compatible, you can't call people on qTox with uTox 0.4.2 and they can't call you. Text chat seems to work.
##

**Comment by GrayHatter** [comment]
I'm guessing your qTox friend isn't on the new ToxAV, ask them to update their client

**Comment by Serg86** [comment]
uTox 0.4.2 to uTox 0.4.2 group voice chat doesn't work, which is where my main problem lies.

**Comment by LittleVulpix** [comment]
I would recommend changing the title from "broke group chat" to "broke group call". Group chats were/are working.

**Comment by Doom032** [comment]
Is group voice chat broken completely? I told Groupbot to create an audio chat, but if I try to get an invite to it, µTox doesn't accept it. But it auto-accepts invites to non-audio groupchats.

**Comment by GrayHatter** [comment]
the code to make it work is still in uTox and ToxAV, it just needs to be put in the correct place and uncommented.

I was waiting on this because Toxcore file transfers looked like they were getting close to their fix, so I was going to wait to do anything until I could get an estimate from @irungentoo about how long an TCP fix would take. But because file transfers are still in progress, I think it's probably better to just fix them now with what currently "works"

**Comment by SmoothDude** [comment]
I know you're doing this in free time, but can you priority this task please ? qTox group calls aren't working properly, hope they will work fine in your client.
