### ISSUE TITLE
Could you please fix the Windows XP build?

### ISSUE THREAD

**Issue by palikacska** [uTox/uTox#609]
The [Windows XP build job](https://build.tox.chat/job/uTox-nightly-FOR-WIN-XP_build_windows_x86_debug/) is failing for about half a year.

The [last successful build](https://build.tox.chat/job/uTox-nightly-FOR-WIN-XP_build_windows_x86_debug/lastSuccessfulBuild/) - also referred as **_Windows XP Version_** on the front page / README.md - crashes immediately when started, it's unusable. The [fresh one for x86 Windows](https://build.tox.chat/view/uTox/job/uTox_build_windows_x86_debug/lastSuccessfulBuild/) won't start on XP.

Windows XP is kept running by low-resource computer users who don't want to buy new computers just to have a new OS on it. uTox is the fastest and most resource-efficient Tox client available. I think it's vital to have it for older systems like Windows XP.

**Comment by GrayHatter** [comment]
I have no near term plans to deprecate XP, It's fallen off my radar by mistake. I'll take a look soon. Sorry I missed this!

**Comment by GrayHatter** [comment]
done https://download.utox.io/stable/uTox_winXP.exe

**Comment by palikacska** [comment]
Works. Thank you very much.

**Comment by 2pacman** [comment]
Link returns 403 Forbidden error. Could you please fix it?

**Comment by Sami32** [comment]
@GrayHatter It is still broken again.

**Comment by Rayxone** [comment]
Hello @GrayHatter, 
support for XP seems deprecated now with dead link https://download.utox.io/stable/uTox_winXP.exe ,
this version does not work too
https://build.tox.chat/view/uTox/job/uTox_build_windows_x86_debug/lastSuccessfulBuild/artifact/utox_windows_x86_debug.zip
and when tried 
https://build.tox.chat/job/uTox-nightly-FOR-WIN-XP_build_windows_x86_debug/lastSuccessfulBuild/artifact/utox_nightly.zip
or
https://downloads.utox.io/stable/uTox_win32.exe
those work, but uTox does not keep the settings and each start is fresh one with new TOX ID.
Debug in attachment
[utox debug.txt](https://github.com/uTox/uTox/files/3282679/utox.debug.txt)
there is an issue with diacritics in path, instead of "Data aplikacÝ" must be "Data aplikací"
Any chance how to keep uTox alive on XP, Czech language eddition?
Many thanks in advance.
