### ISSUE TITLE
All randomised nospams start with 0000.

### ISSUE THREAD

**Issue by robinlinden** [uTox/uTox#665]
Tested on Windows 10.
![image](https://cloud.githubusercontent.com/assets/8304462/22263162/c87a5146-e273-11e6-8c10-2f53e42d12ff.png)

**Comment by GrayHatter** [comment]
http://s2.quickmeme.com/img/15/15bda5ffeac925a812b167ebde5b87abc8767fec213508fd7344e620028221c9.jpg

**Comment by GrayHatter** [comment]
@endoffile78 @robinlinden clearly we need to abstract rand() for uTox because this is a windows only bug. Do we want to fix this as a one off? Or write a native wrapper for rand(), to coerce windows into sane behaviour? 

(I'm doing something similar for groupchats to generate an appropriate color for nicks.)

**Comment by robinlinden** [comment]
The problem is that Windows rand() function only returns up to `32767`.
See: https://msdn.microsoft.com/en-us/library/398ax69y.aspx#Anchor_2

**Comment by cebe** [comment]
> (I'm doing something similar for groupchats to generate an appropriate color for nicks.)

I would prefer the nick color to be deterministically determined from the name so it is the same among different instances.

**Comment by GrayHatter** [comment]
@cebe I'm fine with that, but not about using the name. because then it could change across restarts. I'd rather we use something other than the name (ToxID)

**Comment by GrayHatter** [comment]
per irc -- Fixed
