### ISSUE TITLE
Dropdown menus not working properly

### ISSUE THREAD

**Issue by justicenode** [uTox/uTox#789]
In Version: 0.13.0

- Drop-down menus instantly closes. Which means you have to hold down the mouse in order to select another option.
- Sometimes the drop-down is only partially visible (see image).

![utox bug](https://cloud.githubusercontent.com/assets/26402137/24607277/2ec0934c-1871-11e7-9b27-3dbbdb9d1f96.png)

**Comment by GrayHatter** [comment]
This is an intentional bug. If the screen isn't big enough to draw the whole list, uTox had no way of displaying the list. Currently, you can select on closer to the entry you want, and the list will "move".

There's a few ways I know will fix this, but I haven't made the time to fix it yet.

(Anyone who wants to try to fix it, options to consider -> 
 * if the mouse doesn't move before mup, leave the window open
 * "scroll" the window with move up/down delta
 * use the new popup windows to create a new window detached from uTox to display the full option list.
)

**Comment by GrayHatter** [comment]
shouldn't be too hard to do this...

if the dropdown is opened, set click_mouse_x&y, if mouse up and mouse_xy is unchanged, lock it open, then unlock when the mousexy
